package belhasa;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abhilasha Gupta
 */
public class Home_Belhasa extends javax.swing.JFrame {

    /**
     * Creates new form Home_Belhasa
     */
    
    public Home_Belhasa() {
        initComponents();
        closeAllFrames();
        MainLoginFrame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        desktopPane = new javax.swing.JDesktopPane();
        MainLoginFrame = new javax.swing.JInternalFrame();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        AdminLoginFrame = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        StudentLoginFrame = new javax.swing.JInternalFrame();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        AdminHomeFrame = new javax.swing.JInternalFrame();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        ApproveNewStudents = new javax.swing.JInternalFrame();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        StudentsSignUpFrame = new javax.swing.JInternalFrame();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        St_SignUp_firstName_Textfield = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        St_SignUp_lastName_Textfield = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        St_SignUp_Nationality_Textfield = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        St_SignUp_EmiratesId_Textfield = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        ConfirmNotificationModeFrame = new javax.swing.JInternalFrame();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        InstantRegisterFrame = new javax.swing.JInternalFrame();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        LessonsFrame = new javax.swing.JInternalFrame();
        Lessons_Label = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        LS_Table = new javax.swing.JTable();
        Lessons_Add_Btn = new javax.swing.JButton();
        Lessons_Delete_Btn = new javax.swing.JButton();
        Lessons_Enter_Btn = new javax.swing.JButton();
        LessonContentFrame = new javax.swing.JInternalFrame();
        LsContent_Label = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        LsContent_Textarea = new javax.swing.JTextArea();
        LsContent_Update_Btn = new javax.swing.JButton();
        LsContent_Qstn_Btn = new javax.swing.JButton();
        AddLessonFrame = new javax.swing.JInternalFrame();
        Add_Lesson_Label = new javax.swing.JLabel();
        Add_Lesson_Lsn_Label = new javax.swing.JLabel();
        Add_Lesson_Lsn_Textfield = new javax.swing.JTextField();
        Add_Lesson_Add_Btn = new javax.swing.JButton();
        QuestionsFrame = new javax.swing.JInternalFrame();
        Qstn_Label = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Qstn_Table = new javax.swing.JTable();
        Qstn_Qstn_Label = new javax.swing.JLabel();
        Qstn_Textfield = new javax.swing.JTextField();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        qstn_Add_Btn = new javax.swing.JButton();
        Qstn_Delete_Btn = new javax.swing.JButton();
        Qstn_Update_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));
        desktopPane.setPreferredSize(new java.awt.Dimension(1253, 1173));

        MainLoginFrame.setVisible(true);

        jButton1.setText("Admin Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Student Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("LOGIN");

        javax.swing.GroupLayout MainLoginFrameLayout = new javax.swing.GroupLayout(MainLoginFrame.getContentPane());
        MainLoginFrame.getContentPane().setLayout(MainLoginFrameLayout);
        MainLoginFrameLayout.setHorizontalGroup(
            MainLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLoginFrameLayout.createSequentialGroup()
                .addGroup(MainLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainLoginFrameLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jButton1)
                        .addGap(130, 130, 130)
                        .addComponent(jButton2))
                    .addGroup(MainLoginFrameLayout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainLoginFrameLayout.setVerticalGroup(
            MainLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLoginFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(111, 111, 111)
                .addGroup(MainLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(82, 82, 82))
        );

        desktopPane.add(MainLoginFrame);

        AdminLoginFrame.setVisible(true);

        jLabel1.setText("Select language");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("English");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Arabic");

        jLabel2.setText("User Name");

        jLabel3.setText("Password");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jButton3.setText("Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Admin Login");

        javax.swing.GroupLayout AdminLoginFrameLayout = new javax.swing.GroupLayout(AdminLoginFrame.getContentPane());
        AdminLoginFrame.getContentPane().setLayout(AdminLoginFrameLayout);
        AdminLoginFrameLayout.setHorizontalGroup(
            AdminLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLoginFrameLayout.createSequentialGroup()
                .addGroup(AdminLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminLoginFrameLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(AdminLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(145, 145, 145)
                        .addGroup(AdminLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AdminLoginFrameLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminLoginFrameLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(239, 239, 239)
                .addGroup(AdminLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34))
        );
        AdminLoginFrameLayout.setVerticalGroup(
            AdminLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLoginFrameLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(AdminLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(40, 40, 40)
                .addGroup(AdminLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(AdminLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        desktopPane.add(AdminLoginFrame);

        StudentLoginFrame.setVisible(true);

        jLabel19.setText("Students Login ");

        jLabel20.setText("Student Id");

        jLabel21.setText("Password");

        jButton12.setText("Sign In");

        jButton13.setText("Sign Up");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentLoginFrameLayout = new javax.swing.GroupLayout(StudentLoginFrame.getContentPane());
        StudentLoginFrame.getContentPane().setLayout(StudentLoginFrameLayout);
        StudentLoginFrameLayout.setHorizontalGroup(
            StudentLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentLoginFrameLayout.createSequentialGroup()
                .addGroup(StudentLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentLoginFrameLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel19))
                    .addGroup(StudentLoginFrameLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(StudentLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(108, 108, 108)
                        .addGroup(StudentLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(StudentLoginFrameLayout.createSequentialGroup()
                                .addComponent(jButton12)
                                .addGap(57, 57, 57)
                                .addComponent(jButton13))
                            .addComponent(jTextField11)
                            .addComponent(jTextField10))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StudentLoginFrameLayout.setVerticalGroup(
            StudentLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentLoginFrameLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel19)
                .addGap(53, 53, 53)
                .addGroup(StudentLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(StudentLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(StudentLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton13))
                .addGap(61, 61, 61))
        );

        desktopPane.add(StudentLoginFrame);

        AdminHomeFrame.setVisible(true);

        jButton4.setText(" New Students");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Student Details");

        jButton7.setText("Results");

        jButton8.setText("Change Password");

        jButton9.setText("Logout");

        jButton14.setText("License Category");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminHomeFrameLayout = new javax.swing.GroupLayout(AdminHomeFrame.getContentPane());
        AdminHomeFrame.getContentPane().setLayout(AdminHomeFrameLayout);
        AdminHomeFrameLayout.setHorizontalGroup(
            AdminHomeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminHomeFrameLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(AdminHomeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminHomeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AdminHomeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(157, 157, 157))
        );
        AdminHomeFrameLayout.setVerticalGroup(
            AdminHomeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminHomeFrameLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(AdminHomeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(54, 54, 54)
                .addGroup(AdminHomeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton14))
                .addGap(56, 56, 56)
                .addGroup(AdminHomeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktopPane.add(AdminHomeFrame);

        ApproveNewStudents.setVisible(true);

        jLabel5.setText("New Students");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton10.setText("Approve");

        javax.swing.GroupLayout ApproveNewStudentsLayout = new javax.swing.GroupLayout(ApproveNewStudents.getContentPane());
        ApproveNewStudents.getContentPane().setLayout(ApproveNewStudentsLayout);
        ApproveNewStudentsLayout.setHorizontalGroup(
            ApproveNewStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApproveNewStudentsLayout.createSequentialGroup()
                .addGroup(ApproveNewStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ApproveNewStudentsLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel5))
                    .addGroup(ApproveNewStudentsLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ApproveNewStudentsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        ApproveNewStudentsLayout.setVerticalGroup(
            ApproveNewStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApproveNewStudentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addGap(23, 23, 23))
        );

        desktopPane.add(ApproveNewStudents);

        StudentsSignUpFrame.setVisible(true);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Sign Up");

        jLabel8.setText("Its free and will always be.");

        jLabel9.setText("First Name");

        jLabel10.setText("Last Name");

        jLabel11.setText("Picture");

        jLabel12.setText("I am ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender" }));

        jLabel13.setText("Birthday");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year" }));

        jButton11.setText("Register");

        jLabel14.setText("Nationality");

        jLabel15.setText("Passport No.");

        jLabel16.setText("Emirates Id");

        jLabel17.setText("Marital Status");

        jLabel18.setText("Age");

        jTextField9.setEditable(false);

        javax.swing.GroupLayout StudentsSignUpFrameLayout = new javax.swing.GroupLayout(StudentsSignUpFrame.getContentPane());
        StudentsSignUpFrame.getContentPane().setLayout(StudentsSignUpFrameLayout);
        StudentsSignUpFrameLayout.setHorizontalGroup(
            StudentsSignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentsSignUpFrameLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(StudentsSignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentsSignUpFrameLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(StudentsSignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(StudentsSignUpFrameLayout.createSequentialGroup()
                        .addGroup(StudentsSignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StudentsSignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(StudentsSignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGroup(StudentsSignUpFrameLayout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(1, 1, 1)))
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel18))
                        .addGap(36, 36, 36)
                        .addGroup(StudentsSignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StudentsSignUpFrameLayout.createSequentialGroup()
                                .addComponent(jButton11)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(StudentsSignUpFrameLayout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentsSignUpFrameLayout.createSequentialGroup()
                                .addGroup(StudentsSignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(StudentsSignUpFrameLayout.createSequentialGroup()
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(St_SignUp_EmiratesId_Textfield, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(St_SignUp_Nationality_Textfield, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(St_SignUp_lastName_Textfield, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(St_SignUp_firstName_Textfield, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(46, 46, 46)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))))))
        );
        StudentsSignUpFrameLayout.setVerticalGroup(
            StudentsSignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentsSignUpFrameLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StudentsSignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentsSignUpFrameLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(32, 32, 32)
                        .addGroup(StudentsSignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(StudentsSignUpFrameLayout.createSequentialGroup()
                                .addGroup(StudentsSignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(St_SignUp_firstName_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(StudentsSignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(St_SignUp_lastName_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(StudentsSignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(St_SignUp_Nationality_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(StudentsSignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(StudentsSignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(St_SignUp_EmiratesId_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(StudentsSignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(StudentsSignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(StudentsSignUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel18))
                    .addGroup(StudentsSignUpFrameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addComponent(jButton11)
                .addContainerGap())
        );

        desktopPane.add(StudentsSignUpFrame);

        ConfirmNotificationModeFrame.setVisible(true);

        jRadioButton3.setText("Email Notification");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("Instant Registration");

        javax.swing.GroupLayout ConfirmNotificationModeFrameLayout = new javax.swing.GroupLayout(ConfirmNotificationModeFrame.getContentPane());
        ConfirmNotificationModeFrame.getContentPane().setLayout(ConfirmNotificationModeFrameLayout);
        ConfirmNotificationModeFrameLayout.setHorizontalGroup(
            ConfirmNotificationModeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmNotificationModeFrameLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(ConfirmNotificationModeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ConfirmNotificationModeFrameLayout.setVerticalGroup(
            ConfirmNotificationModeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmNotificationModeFrameLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jRadioButton3)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktopPane.add(ConfirmNotificationModeFrame);

        InstantRegisterFrame.setVisible(true);

        jLabel22.setText("Instant Registration");

        jLabel23.setText("Admin Password");

        jButton6.setText("Activate Account");

        javax.swing.GroupLayout InstantRegisterFrameLayout = new javax.swing.GroupLayout(InstantRegisterFrame.getContentPane());
        InstantRegisterFrame.getContentPane().setLayout(InstantRegisterFrameLayout);
        InstantRegisterFrameLayout.setHorizontalGroup(
            InstantRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InstantRegisterFrameLayout.createSequentialGroup()
                .addGroup(InstantRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InstantRegisterFrameLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel23)
                        .addGap(104, 104, 104)
                        .addGroup(InstantRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(InstantRegisterFrameLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel22)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InstantRegisterFrameLayout.setVerticalGroup(
            InstantRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InstantRegisterFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(66, 66, 66)
                .addGroup(InstantRegisterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktopPane.add(InstantRegisterFrame);

        LessonsFrame.setVisible(true);

        Lessons_Label.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Lessons_Label.setText("LESSONS");

        LS_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Lessons"
            }
        ));
        jScrollPane2.setViewportView(LS_Table);

        Lessons_Add_Btn.setText("Add");

        Lessons_Delete_Btn.setText("Delete");

        Lessons_Enter_Btn.setText("Enter");

        javax.swing.GroupLayout LessonsFrameLayout = new javax.swing.GroupLayout(LessonsFrame.getContentPane());
        LessonsFrame.getContentPane().setLayout(LessonsFrameLayout);
        LessonsFrameLayout.setHorizontalGroup(
            LessonsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LessonsFrameLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(Lessons_Label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LessonsFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LessonsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(LessonsFrameLayout.createSequentialGroup()
                        .addComponent(Lessons_Add_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(Lessons_Delete_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Lessons_Enter_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        LessonsFrameLayout.setVerticalGroup(
            LessonsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LessonsFrameLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Lessons_Label)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(LessonsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lessons_Add_Btn)
                    .addComponent(Lessons_Delete_Btn)
                    .addComponent(Lessons_Enter_Btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktopPane.add(LessonsFrame);

        LessonContentFrame.setVisible(true);

        LsContent_Label.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        LsContent_Label.setText("Lesson contents");

        LsContent_Textarea.setColumns(20);
        LsContent_Textarea.setRows(5);
        jScrollPane3.setViewportView(LsContent_Textarea);

        LsContent_Update_Btn.setText("Update");

        LsContent_Qstn_Btn.setText("Questions");

        javax.swing.GroupLayout LessonContentFrameLayout = new javax.swing.GroupLayout(LessonContentFrame.getContentPane());
        LessonContentFrame.getContentPane().setLayout(LessonContentFrameLayout);
        LessonContentFrameLayout.setHorizontalGroup(
            LessonContentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LessonContentFrameLayout.createSequentialGroup()
                .addGroup(LessonContentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LessonContentFrameLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(LsContent_Label))
                    .addGroup(LessonContentFrameLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(LessonContentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LessonContentFrameLayout.createSequentialGroup()
                                .addComponent(LsContent_Update_Btn)
                                .addGap(112, 112, 112)
                                .addComponent(LsContent_Qstn_Btn)
                                .addGap(25, 25, 25)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LessonContentFrameLayout.setVerticalGroup(
            LessonContentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LessonContentFrameLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LsContent_Label)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LessonContentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LsContent_Update_Btn)
                    .addComponent(LsContent_Qstn_Btn))
                .addGap(34, 34, 34))
        );

        desktopPane.add(LessonContentFrame);

        AddLessonFrame.setVisible(true);

        Add_Lesson_Label.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Add_Lesson_Label.setText("ADD LESSONS");

        Add_Lesson_Lsn_Label.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Add_Lesson_Lsn_Label.setText("LESSON");

        Add_Lesson_Add_Btn.setText("Add");

        javax.swing.GroupLayout AddLessonFrameLayout = new javax.swing.GroupLayout(AddLessonFrame.getContentPane());
        AddLessonFrame.getContentPane().setLayout(AddLessonFrameLayout);
        AddLessonFrameLayout.setHorizontalGroup(
            AddLessonFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLessonFrameLayout.createSequentialGroup()
                .addGroup(AddLessonFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddLessonFrameLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(Add_Lesson_Lsn_Label)
                        .addGap(71, 71, 71)
                        .addGroup(AddLessonFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Add_Lesson_Add_Btn)
                            .addComponent(Add_Lesson_Lsn_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AddLessonFrameLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(Add_Lesson_Label)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        AddLessonFrameLayout.setVerticalGroup(
            AddLessonFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLessonFrameLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(Add_Lesson_Label)
                .addGap(57, 57, 57)
                .addGroup(AddLessonFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Add_Lesson_Lsn_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_Lesson_Lsn_Label))
                .addGap(42, 42, 42)
                .addComponent(Add_Lesson_Add_Btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktopPane.add(AddLessonFrame);

        QuestionsFrame.setVisible(true);

        Qstn_Label.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Qstn_Label.setText("QUESTIONS");
        QuestionsFrame.getContentPane().add(Qstn_Label);

        Qstn_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Question", "Option1", "Option2", "Option3", "Answer"
            }
        ));
        jScrollPane4.setViewportView(Qstn_Table);

        QuestionsFrame.getContentPane().add(jScrollPane4);

        Qstn_Qstn_Label.setText("QUESTION");
        QuestionsFrame.getContentPane().add(Qstn_Qstn_Label);
        QuestionsFrame.getContentPane().add(Qstn_Textfield);

        buttonGroup3.add(jRadioButton6);
        jRadioButton6.setText("jRadioButton3");
        QuestionsFrame.getContentPane().add(jRadioButton6);

        buttonGroup3.add(jRadioButton7);
        jRadioButton7.setText("jRadioButton4");
        QuestionsFrame.getContentPane().add(jRadioButton7);

        buttonGroup3.add(jRadioButton5);
        jRadioButton5.setText("jRadioButton5");
        QuestionsFrame.getContentPane().add(jRadioButton5);

        qstn_Add_Btn.setText("Add");
        QuestionsFrame.getContentPane().add(qstn_Add_Btn);

        Qstn_Delete_Btn.setText("Delete");
        QuestionsFrame.getContentPane().add(Qstn_Delete_Btn);

        Qstn_Update_Btn.setText("Update");
        QuestionsFrame.getContentPane().add(Qstn_Update_Btn);

        desktopPane.add(QuestionsFrame);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(335, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void closeAllFrames() {
        MainLoginFrame.setVisible(false);
        AdminHomeFrame.setVisible(false);
        StudentLoginFrame.setVisible(false);
        AdminLoginFrame.setVisible(false);
        ApproveNewStudents.setVisible(false);
        StudentsSignUpFrame.setVisible(false);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        closeAllFrames();
        AdminHomeFrame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         closeAllFrames();
        StudentLoginFrame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         closeAllFrames();
        AdminHomeFrame.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         closeAllFrames();
        ApproveNewStudents.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        closeAllFrames();
        StudentsSignUpFrame.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        UserRegistration_MailToAdmin();
    }//GEN-LAST:event_jRadioButton3ActionPerformed

     private void UserRegistration_MailToAdmin()
    {
        String messageBody = null;
            String[] recipients = new String[1];
            String[] bccRecipients = new String[]{""};
            String subject = "New User Registered";
            StringBuffer messageBodyBuffer = new StringBuffer();
            
                    messageBodyBuffer.append("Hi Admin");
            
                    //recipients[0] = adusr_email_textfield.getText(); //admin email id
                    messageBodyBuffer.append("</br>");
                    messageBodyBuffer.append("</br>");
                    messageBodyBuffer.append("A new student has sign up in the application.");
                    messageBodyBuffer.append("</br>");
                    messageBodyBuffer.append("</br>");
                    messageBodyBuffer.append("Student Details: ");
                    messageBodyBuffer.append("</br>");
                    messageBodyBuffer.append("First Name: ").append(St_SignUp_firstName_Textfield.getText());
                    messageBodyBuffer.append("</br>");
                    messageBodyBuffer.append("Last Name: ").append(St_SignUp_lastName_Textfield.getText());
                    messageBodyBuffer.append("</br>");
                    messageBodyBuffer.append("Nationality: ").append(St_SignUp_Nationality_Textfield.getText());
                    messageBodyBuffer.append("</br>");
                    messageBodyBuffer.append("Emirates Id: ").append(St_SignUp_EmiratesId_Textfield.getText());
                    messageBodyBuffer.append("</br>");
                    messageBodyBuffer.append("</br>");
                    messageBodyBuffer.append("</br>");
                    messageBodyBuffer.append("Regards,");
                    messageBodyBuffer.append("</br>");
                    messageBodyBuffer.append("Team");
                    messageBody = messageBodyBuffer.toString();

                    new MailUtil().sendMail(recipients, bccRecipients, subject, messageBody);
                   
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Belhasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Belhasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Belhasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Belhasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Belhasa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame AddLessonFrame;
    private javax.swing.JButton Add_Lesson_Add_Btn;
    private javax.swing.JLabel Add_Lesson_Label;
    private javax.swing.JLabel Add_Lesson_Lsn_Label;
    private javax.swing.JTextField Add_Lesson_Lsn_Textfield;
    private javax.swing.JInternalFrame AdminHomeFrame;
    private javax.swing.JInternalFrame AdminLoginFrame;
    private javax.swing.JInternalFrame ApproveNewStudents;
    private javax.swing.JInternalFrame ConfirmNotificationModeFrame;
    private javax.swing.JInternalFrame InstantRegisterFrame;
    private javax.swing.JTable LS_Table;
    private javax.swing.JInternalFrame LessonContentFrame;
    private javax.swing.JInternalFrame LessonsFrame;
    private javax.swing.JButton Lessons_Add_Btn;
    private javax.swing.JButton Lessons_Delete_Btn;
    private javax.swing.JButton Lessons_Enter_Btn;
    private javax.swing.JLabel Lessons_Label;
    private javax.swing.JLabel LsContent_Label;
    private javax.swing.JButton LsContent_Qstn_Btn;
    private javax.swing.JTextArea LsContent_Textarea;
    private javax.swing.JButton LsContent_Update_Btn;
    private javax.swing.JInternalFrame MainLoginFrame;
    private javax.swing.JButton Qstn_Delete_Btn;
    private javax.swing.JLabel Qstn_Label;
    private javax.swing.JLabel Qstn_Qstn_Label;
    private javax.swing.JTable Qstn_Table;
    private javax.swing.JTextField Qstn_Textfield;
    private javax.swing.JButton Qstn_Update_Btn;
    private javax.swing.JInternalFrame QuestionsFrame;
    private javax.swing.JTextField St_SignUp_EmiratesId_Textfield;
    private javax.swing.JTextField St_SignUp_Nationality_Textfield;
    private javax.swing.JTextField St_SignUp_firstName_Textfield;
    private javax.swing.JTextField St_SignUp_lastName_Textfield;
    private javax.swing.JInternalFrame StudentLoginFrame;
    private javax.swing.JInternalFrame StudentsSignUpFrame;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton qstn_Add_Btn;
    // End of variables declaration//GEN-END:variables
}
