package belhasa;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abhilasha Gupta
 */
public class Home_Belhasa extends javax.swing.JFrame {

    /**
     * Creates new form Home_Belhasa
     */
    
    public Home_Belhasa() {
        initComponents();
        closeAllFrames();
        MainLoginFrame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        desktopPane = new javax.swing.JDesktopPane();
        MainLoginFrame = new javax.swing.JInternalFrame();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        AdminLoginFrame = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        StudentLoginFrame = new javax.swing.JInternalFrame();
        AdminHomeFrame = new javax.swing.JInternalFrame();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        ApproveNewStudents = new javax.swing.JInternalFrame();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        StudentsHomeFrame = new javax.swing.JInternalFrame();
        St_Home_ChangePswd_Btn = new javax.swing.JButton();
        AdminChangepasswordFrame = new javax.swing.JInternalFrame();
        Ad_changepswd_Label = new javax.swing.JLabel();
        Ad_changepswd_password_Label = new javax.swing.JLabel();
        Ad_changepswd_Confpswd_Label = new javax.swing.JLabel();
        Ad_changepswd_password_Textfield = new javax.swing.JTextField();
        Ad_changepswd_Confpswd_Textfieldl = new javax.swing.JTextField();
        Ad_changepswd_sUBMIT_Btn = new javax.swing.JButton();
        LicenseCategoryFrame = new javax.swing.JInternalFrame();
        LcCategory_Label = new javax.swing.JLabel();
        LcCategory_LMV_RdBtn = new javax.swing.JRadioButton();
        LcCategory_MC_RdBtn = new javax.swing.JRadioButton();
        LcCategory_HVT_RdBtn = new javax.swing.JRadioButton();
        LessonsFrame = new javax.swing.JInternalFrame();
        Lessons_Label = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        LS_Table = new javax.swing.JTable();
        Lessons_Add_Btn = new javax.swing.JButton();
        Lessons_Delete_Btn = new javax.swing.JButton();
        Lessons_Enter_Btn = new javax.swing.JButton();
        LessonContentFrame = new javax.swing.JInternalFrame();
        LsContent_Label = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        LsContent_Textarea = new javax.swing.JTextArea();
        LsContent_Update_Btn = new javax.swing.JButton();
        LsContent_Qstn_Btn = new javax.swing.JButton();
        AddLessonFrame = new javax.swing.JInternalFrame();
        Add_Lesson_Label = new javax.swing.JLabel();
        Add_Lesson_Lsn_Label = new javax.swing.JLabel();
        Add_Lesson_Lsn_Textfield = new javax.swing.JTextField();
        Add_Lesson_Add_Btn = new javax.swing.JButton();
        QuestionsFrame = new javax.swing.JInternalFrame();
        Qstn_Label = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Qstn_Table = new javax.swing.JTable();
        Qstn_Qstn_Label = new javax.swing.JLabel();
        Qstn_Textfield = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        qstn_Add_Btn = new javax.swing.JButton();
        Qstn_Delete_Btn = new javax.swing.JButton();
        Qstn_Update_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));
        desktopPane.setPreferredSize(new java.awt.Dimension(1253, 1173));

        MainLoginFrame.setVisible(true);

        jButton1.setText("Admin Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Student Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("LOGIN");

        javax.swing.GroupLayout MainLoginFrameLayout = new javax.swing.GroupLayout(MainLoginFrame.getContentPane());
        MainLoginFrame.getContentPane().setLayout(MainLoginFrameLayout);
        MainLoginFrameLayout.setHorizontalGroup(
            MainLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLoginFrameLayout.createSequentialGroup()
                .addGroup(MainLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainLoginFrameLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jButton1)
                        .addGap(130, 130, 130)
                        .addComponent(jButton2))
                    .addGroup(MainLoginFrameLayout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel6)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        MainLoginFrameLayout.setVerticalGroup(
            MainLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLoginFrameLayout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(111, 111, 111)
                .addGroup(MainLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(82, 82, 82))
        );

        AdminLoginFrame.setVisible(true);

        jLabel1.setText("Select language");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("English");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Arabic");

        jLabel2.setText("User Name");

        jLabel3.setText("Password");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jButton3.setText("Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout AdminLoginFrameLayout = new javax.swing.GroupLayout(AdminLoginFrame.getContentPane());
        AdminLoginFrame.getContentPane().setLayout(AdminLoginFrameLayout);
        AdminLoginFrameLayout.setHorizontalGroup(
            AdminLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLoginFrameLayout.createSequentialGroup()
                .addGroup(AdminLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminLoginFrameLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(AdminLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(145, 145, 145)
                        .addGroup(AdminLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AdminLoginFrameLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminLoginFrameLayout.createSequentialGroup()
                .addGap(0, 240, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(239, 239, 239)
                .addGroup(AdminLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34))
        );
        AdminLoginFrameLayout.setVerticalGroup(
            AdminLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLoginFrameLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(AdminLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(40, 40, 40)
                .addGroup(AdminLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(AdminLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        StudentLoginFrame.setVisible(true);

        javax.swing.GroupLayout StudentLoginFrameLayout = new javax.swing.GroupLayout(StudentLoginFrame.getContentPane());
        StudentLoginFrame.getContentPane().setLayout(StudentLoginFrameLayout);
        StudentLoginFrameLayout.setHorizontalGroup(
            StudentLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 751, Short.MAX_VALUE)
        );
        StudentLoginFrameLayout.setVerticalGroup(
            StudentLoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );

        AdminHomeFrame.setVisible(true);

        jButton4.setText(" New Students");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Student Details");

        jButton6.setText("Questionaire");

        jButton7.setText("Results");

        jButton8.setText("Change Password");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Logout");

        javax.swing.GroupLayout AdminHomeFrameLayout = new javax.swing.GroupLayout(AdminHomeFrame.getContentPane());
        AdminHomeFrame.getContentPane().setLayout(AdminHomeFrameLayout);
        AdminHomeFrameLayout.setHorizontalGroup(
            AdminHomeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminHomeFrameLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(AdminHomeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addGroup(AdminHomeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(157, 157, 157))
        );
        AdminHomeFrameLayout.setVerticalGroup(
            AdminHomeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminHomeFrameLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(AdminHomeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(54, 54, 54)
                .addGroup(AdminHomeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(56, 56, 56)
                .addGroup(AdminHomeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        ApproveNewStudents.setVisible(true);

        jLabel5.setText("New Students");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton10.setText("Approve");

        javax.swing.GroupLayout ApproveNewStudentsLayout = new javax.swing.GroupLayout(ApproveNewStudents.getContentPane());
        ApproveNewStudents.getContentPane().setLayout(ApproveNewStudentsLayout);
        ApproveNewStudentsLayout.setHorizontalGroup(
            ApproveNewStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApproveNewStudentsLayout.createSequentialGroup()
                .addGroup(ApproveNewStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ApproveNewStudentsLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel5))
                    .addGroup(ApproveNewStudentsLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ApproveNewStudentsLayout.createSequentialGroup()
                .addGap(0, 65, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        ApproveNewStudentsLayout.setVerticalGroup(
            ApproveNewStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApproveNewStudentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addGap(23, 23, 23))
        );

        StudentsHomeFrame.setVisible(true);

        St_Home_ChangePswd_Btn.setText("CHANGE PASSWORD");

        javax.swing.GroupLayout StudentsHomeFrameLayout = new javax.swing.GroupLayout(StudentsHomeFrame.getContentPane());
        StudentsHomeFrame.getContentPane().setLayout(StudentsHomeFrameLayout);
        StudentsHomeFrameLayout.setHorizontalGroup(
            StudentsHomeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentsHomeFrameLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(St_Home_ChangePswd_Btn)
                .addContainerGap(436, Short.MAX_VALUE))
        );
        StudentsHomeFrameLayout.setVerticalGroup(
            StudentsHomeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentsHomeFrameLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(St_Home_ChangePswd_Btn)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        AdminChangepasswordFrame.setVisible(true);

        Ad_changepswd_Label.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Ad_changepswd_Label.setText("CHANGE PASSWORD");

        Ad_changepswd_password_Label.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Ad_changepswd_password_Label.setText("Password");

        Ad_changepswd_Confpswd_Label.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Ad_changepswd_Confpswd_Label.setText("Confirm Password");

        Ad_changepswd_sUBMIT_Btn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Ad_changepswd_sUBMIT_Btn.setText("SUBMIT");

        javax.swing.GroupLayout AdminChangepasswordFrameLayout = new javax.swing.GroupLayout(AdminChangepasswordFrame.getContentPane());
        AdminChangepasswordFrame.getContentPane().setLayout(AdminChangepasswordFrameLayout);
        AdminChangepasswordFrameLayout.setHorizontalGroup(
            AdminChangepasswordFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminChangepasswordFrameLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AdminChangepasswordFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminChangepasswordFrameLayout.createSequentialGroup()
                        .addGroup(AdminChangepasswordFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Ad_changepswd_Confpswd_Label)
                            .addComponent(Ad_changepswd_password_Label))
                        .addGap(74, 74, 74)
                        .addGroup(AdminChangepasswordFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Ad_changepswd_sUBMIT_Btn)
                            .addComponent(Ad_changepswd_password_Textfield)
                            .addComponent(Ad_changepswd_Confpswd_Textfieldl, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Ad_changepswd_Label, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        AdminChangepasswordFrameLayout.setVerticalGroup(
            AdminChangepasswordFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminChangepasswordFrameLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(Ad_changepswd_Label)
                .addGap(37, 37, 37)
                .addGroup(AdminChangepasswordFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ad_changepswd_password_Label)
                    .addComponent(Ad_changepswd_password_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(AdminChangepasswordFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ad_changepswd_Confpswd_Label)
                    .addComponent(Ad_changepswd_Confpswd_Textfieldl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(Ad_changepswd_sUBMIT_Btn)
                .addGap(21, 21, 21))
        );

        LicenseCategoryFrame.setVisible(true);

        LcCategory_Label.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        LcCategory_Label.setText("LICENSE CATEGORY");

        buttonGroup2.add(LcCategory_LMV_RdBtn);
        LcCategory_LMV_RdBtn.setText("LMV");

        buttonGroup2.add(LcCategory_MC_RdBtn);
        LcCategory_MC_RdBtn.setText("MC");

        buttonGroup2.add(LcCategory_HVT_RdBtn);
        LcCategory_HVT_RdBtn.setText("HVT");

        javax.swing.GroupLayout LicenseCategoryFrameLayout = new javax.swing.GroupLayout(LicenseCategoryFrame.getContentPane());
        LicenseCategoryFrame.getContentPane().setLayout(LicenseCategoryFrameLayout);
        LicenseCategoryFrameLayout.setHorizontalGroup(
            LicenseCategoryFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LicenseCategoryFrameLayout.createSequentialGroup()
                .addGroup(LicenseCategoryFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LicenseCategoryFrameLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(LicenseCategoryFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LcCategory_MC_RdBtn)
                            .addComponent(LcCategory_LMV_RdBtn)
                            .addComponent(LcCategory_HVT_RdBtn)))
                    .addGroup(LicenseCategoryFrameLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(LcCategory_Label)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        LicenseCategoryFrameLayout.setVerticalGroup(
            LicenseCategoryFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LicenseCategoryFrameLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(LcCategory_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(LcCategory_LMV_RdBtn)
                .addGap(18, 18, 18)
                .addComponent(LcCategory_MC_RdBtn)
                .addGap(32, 32, 32)
                .addComponent(LcCategory_HVT_RdBtn)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        LessonsFrame.setVisible(true);

        Lessons_Label.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Lessons_Label.setText("LESSONS");

        LS_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Lessons"
            }
        ));
        jScrollPane2.setViewportView(LS_Table);

        Lessons_Add_Btn.setText("Add");

        Lessons_Delete_Btn.setText("Delete");

        Lessons_Enter_Btn.setText("Enter");

        javax.swing.GroupLayout LessonsFrameLayout = new javax.swing.GroupLayout(LessonsFrame.getContentPane());
        LessonsFrame.getContentPane().setLayout(LessonsFrameLayout);
        LessonsFrameLayout.setHorizontalGroup(
            LessonsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LessonsFrameLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(Lessons_Label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LessonsFrameLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(LessonsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(LessonsFrameLayout.createSequentialGroup()
                        .addComponent(Lessons_Add_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(Lessons_Delete_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Lessons_Enter_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        LessonsFrameLayout.setVerticalGroup(
            LessonsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LessonsFrameLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Lessons_Label)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(LessonsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lessons_Add_Btn)
                    .addComponent(Lessons_Delete_Btn)
                    .addComponent(Lessons_Enter_Btn))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        LessonContentFrame.setVisible(true);

        LsContent_Label.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        LsContent_Label.setText("Lesson contents");

        LsContent_Textarea.setColumns(20);
        LsContent_Textarea.setRows(5);
        jScrollPane3.setViewportView(LsContent_Textarea);

        LsContent_Update_Btn.setText("Update");

        LsContent_Qstn_Btn.setText("Questions");

        javax.swing.GroupLayout LessonContentFrameLayout = new javax.swing.GroupLayout(LessonContentFrame.getContentPane());
        LessonContentFrame.getContentPane().setLayout(LessonContentFrameLayout);
        LessonContentFrameLayout.setHorizontalGroup(
            LessonContentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LessonContentFrameLayout.createSequentialGroup()
                .addGroup(LessonContentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LessonContentFrameLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(LsContent_Label))
                    .addGroup(LessonContentFrameLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(LessonContentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LessonContentFrameLayout.createSequentialGroup()
                                .addComponent(LsContent_Update_Btn)
                                .addGap(112, 112, 112)
                                .addComponent(LsContent_Qstn_Btn)
                                .addGap(25, 25, 25)))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        LessonContentFrameLayout.setVerticalGroup(
            LessonContentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LessonContentFrameLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LsContent_Label)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(LessonContentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LsContent_Update_Btn)
                    .addComponent(LsContent_Qstn_Btn))
                .addGap(34, 34, 34))
        );

        AddLessonFrame.setVisible(true);

        Add_Lesson_Label.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Add_Lesson_Label.setText("ADD LESSONS");

        Add_Lesson_Lsn_Label.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Add_Lesson_Lsn_Label.setText("LESSON");

        Add_Lesson_Add_Btn.setText("Add");

        javax.swing.GroupLayout AddLessonFrameLayout = new javax.swing.GroupLayout(AddLessonFrame.getContentPane());
        AddLessonFrame.getContentPane().setLayout(AddLessonFrameLayout);
        AddLessonFrameLayout.setHorizontalGroup(
            AddLessonFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLessonFrameLayout.createSequentialGroup()
                .addGroup(AddLessonFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddLessonFrameLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(Add_Lesson_Lsn_Label)
                        .addGap(71, 71, 71)
                        .addGroup(AddLessonFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Add_Lesson_Add_Btn)
                            .addComponent(Add_Lesson_Lsn_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AddLessonFrameLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(Add_Lesson_Label)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        AddLessonFrameLayout.setVerticalGroup(
            AddLessonFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLessonFrameLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(Add_Lesson_Label)
                .addGap(57, 57, 57)
                .addGroup(AddLessonFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Add_Lesson_Lsn_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_Lesson_Lsn_Label))
                .addGap(42, 42, 42)
                .addComponent(Add_Lesson_Add_Btn)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        QuestionsFrame.setVisible(true);

        Qstn_Label.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Qstn_Label.setText("QUESTIONS");

        Qstn_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Question", "Option1", "Option2", "Option3", "Answer"
            }
        ));
        jScrollPane4.setViewportView(Qstn_Table);

        Qstn_Qstn_Label.setText("QUESTION");

        buttonGroup3.add(jRadioButton3);
        jRadioButton3.setText("jRadioButton3");

        buttonGroup3.add(jRadioButton4);
        jRadioButton4.setText("jRadioButton4");

        buttonGroup3.add(jRadioButton5);
        jRadioButton5.setText("jRadioButton5");

        qstn_Add_Btn.setText("Add");

        Qstn_Delete_Btn.setText("Delete");

        Qstn_Update_Btn.setText("Update");

        javax.swing.GroupLayout QuestionsFrameLayout = new javax.swing.GroupLayout(QuestionsFrame.getContentPane());
        QuestionsFrame.getContentPane().setLayout(QuestionsFrameLayout);
        QuestionsFrameLayout.setHorizontalGroup(
            QuestionsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionsFrameLayout.createSequentialGroup()
                .addGroup(QuestionsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuestionsFrameLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(Qstn_Label))
                    .addGroup(QuestionsFrameLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(QuestionsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(QuestionsFrameLayout.createSequentialGroup()
                                .addComponent(Qstn_Qstn_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(QuestionsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton4)
                                    .addComponent(jRadioButton5)
                                    .addComponent(Qstn_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, QuestionsFrameLayout.createSequentialGroup()
                                .addComponent(qstn_Add_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)
                                .addComponent(Qstn_Delete_Btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Qstn_Update_Btn)))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        QuestionsFrameLayout.setVerticalGroup(
            QuestionsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionsFrameLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Qstn_Label)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(QuestionsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Qstn_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Qstn_Qstn_Label))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(QuestionsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qstn_Add_Btn)
                    .addComponent(Qstn_Delete_Btn)
                    .addComponent(Qstn_Update_Btn))
                .addGap(19, 19, 19))
        );

        desktopPane.setLayer(MainLoginFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(AdminLoginFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(StudentLoginFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(AdminHomeFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(ApproveNewStudents, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(StudentsHomeFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(AdminChangepasswordFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(LicenseCategoryFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(LessonsFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(LessonContentFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(AddLessonFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(QuestionsFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainLoginFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AdminLoginFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(StudentLoginFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AdminHomeFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ApproveNewStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(StudentsHomeFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AdminChangepasswordFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LicenseCategoryFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LessonsFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LessonContentFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AddLessonFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(QuestionsFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainLoginFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(724, Short.MAX_VALUE))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AdminLoginFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(StudentLoginFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AdminHomeFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ApproveNewStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(StudentsHomeFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AdminChangepasswordFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LicenseCategoryFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LessonsFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LessonContentFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AddLessonFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(QuestionsFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(335, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void closeAllFrames() {
        MainLoginFrame.setVisible(false);
        AdminHomeFrame.setVisible(false);
        StudentLoginFrame.setVisible(false);
        AdminLoginFrame.setVisible(false);
        ApproveNewStudents.setVisible(false);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        closeAllFrames();
        AdminHomeFrame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         closeAllFrames();
        StudentLoginFrame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         closeAllFrames();
        AdminHomeFrame.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         closeAllFrames();
        ApproveNewStudents.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        closeAllFrames();
        AdminChangepasswordFrame.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Belhasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Belhasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Belhasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Belhasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Belhasa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ad_changepswd_Confpswd_Label;
    private javax.swing.JTextField Ad_changepswd_Confpswd_Textfieldl;
    private javax.swing.JLabel Ad_changepswd_Label;
    private javax.swing.JLabel Ad_changepswd_password_Label;
    private javax.swing.JTextField Ad_changepswd_password_Textfield;
    private javax.swing.JButton Ad_changepswd_sUBMIT_Btn;
    private javax.swing.JInternalFrame AddLessonFrame;
    private javax.swing.JButton Add_Lesson_Add_Btn;
    private javax.swing.JLabel Add_Lesson_Label;
    private javax.swing.JLabel Add_Lesson_Lsn_Label;
    private javax.swing.JTextField Add_Lesson_Lsn_Textfield;
    private javax.swing.JInternalFrame AdminChangepasswordFrame;
    private javax.swing.JInternalFrame AdminHomeFrame;
    private javax.swing.JInternalFrame AdminLoginFrame;
    private javax.swing.JInternalFrame ApproveNewStudents;
    private javax.swing.JTable LS_Table;
    private javax.swing.JRadioButton LcCategory_HVT_RdBtn;
    private javax.swing.JRadioButton LcCategory_LMV_RdBtn;
    private javax.swing.JLabel LcCategory_Label;
    private javax.swing.JRadioButton LcCategory_MC_RdBtn;
    private javax.swing.JInternalFrame LessonContentFrame;
    private javax.swing.JInternalFrame LessonsFrame;
    private javax.swing.JButton Lessons_Add_Btn;
    private javax.swing.JButton Lessons_Delete_Btn;
    private javax.swing.JButton Lessons_Enter_Btn;
    private javax.swing.JLabel Lessons_Label;
    private javax.swing.JInternalFrame LicenseCategoryFrame;
    private javax.swing.JLabel LsContent_Label;
    private javax.swing.JButton LsContent_Qstn_Btn;
    private javax.swing.JTextArea LsContent_Textarea;
    private javax.swing.JButton LsContent_Update_Btn;
    private javax.swing.JInternalFrame MainLoginFrame;
    private javax.swing.JButton Qstn_Delete_Btn;
    private javax.swing.JLabel Qstn_Label;
    private javax.swing.JLabel Qstn_Qstn_Label;
    private javax.swing.JTable Qstn_Table;
    private javax.swing.JTextField Qstn_Textfield;
    private javax.swing.JButton Qstn_Update_Btn;
    private javax.swing.JInternalFrame QuestionsFrame;
    private javax.swing.JButton St_Home_ChangePswd_Btn;
    private javax.swing.JInternalFrame StudentLoginFrame;
    private javax.swing.JInternalFrame StudentsHomeFrame;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton qstn_Add_Btn;
    // End of variables declaration//GEN-END:variables
}
